Removing Node inheritance and Node properties [EPIC].
This is an EPIC refactoring commit.

Moved Nodes plugin to Component plugin and
removed the MeshNode class files.

Controls for node transforms have been added to the World Editor.
The tree view for properties has been moved to the component group box,
and will now show the fields in the protobuf message for selected
components.
NodeModel has been heavily downgraded and now just shows a list of
components.

Also changed the pre-commit hook so it is no longer necesary to
manually run the format-code target.

diff --git a/cmake/pre-commit.in b/cmake/pre-commit.in
--- a/cmake/pre-commit.in
+++ b/cmake/pre-commit.in
@@ -12,15 +12,6 @@ YEAR=`date +"%Y"`
 FILES=`git diff --cached $against --name-only --diff-filter=ACMR | grep -E "\.(c|cpp|h|hpp)$"`
 PYTHON_FILES=`git diff --cached $against --name-only --diff-filter=ACMR | grep -E "\.(py)$"`
 PROTO_FILES=`git diff --cached $against --name-only --diff-filter=ACMR | grep -E "\.(proto)$"`
-for FILE in $FILES; do
-	${ASTYLE_EXECUTABLE} ${ASTYLE_OPTIONS} < $FILE | cmp -s $FILE -
-	if [ $? -ne 0 ]; then
-		echo "[!] $FILE does not respect coding style," >&2
-		echo "[!] please build the 'format-code' target." >&2
-		echo "[!] For example make format-code" >&2
-		exit 1
-	fi
-done
 
 EXIT_CODE=0
 for FILE in $FILES; do
@@ -64,3 +55,13 @@ if [ $EXIT_CODE -ne 0 ]; then
     echo "[!] For example: /* Copyright (C) $YEAR */." >&2
     exit 1
 fi
+
+for FILE in $FILES; do
+	${ASTYLE_EXECUTABLE} --quiet ${ASTYLE_OPTIONS} $FILE
+	if [ $? -ne 0 ]; then
+		echo "[!] Formating $FILE failed," >&2
+		echo "[!] is astyle installed?." >&2
+		exit 1
+	fi
+	git add $FILE
+done
