Added Base64 encoding and decoding functions.
Binary strings in text protobuf files are too long,
sometimes 3 or 4 times the original binary array.

Binary files such as images are troublesome for git,
which is why their inclussion has been kept to a minimum
in favour of SVG images, but it will be necesary at some point
to add all kinds of 'source' binary files, these shall
be base64 encoded.

diff --git a/cmake/pre-commit.in b/cmake/pre-commit.in
--- a/cmake/pre-commit.in
+++ b/cmake/pre-commit.in
@@ -30,6 +30,19 @@ if [ $EXIT_CODE -ne 0 ]; then
     exit 1
 fi
 
+# Remove Tabs
+for FILE in $TEXT_FILES; do
+	"${SED_EXECUTABLE}" -i 's/\t/    /' $FILE
+	if [ $? -ne 0 ]; then
+		echo "[!] $FILE" >&2
+        EXIT_CODE=1
+	fi
+done
+if [ $EXIT_CODE -ne 0 ]; then
+    echo "[!] sed failed when removing tabs." >&2
+    exit 1
+fi
+
 # Format CMake Files only if the executable exists
 if [ -f "${CMAKE_FORMAT_EXECUTABLE}" ]; then
 	for FILE in $CMAKE_FILES; do
